// 定义天气时钟主页状态 GIF 的稳定尺寸与帧布局契约。
#pragma once

// Generated by scripts/generate_status_gif.py. Do not edit manually.
inline constexpr int STATUS_GIF_WIDTH = 84;
inline constexpr int STATUS_GIF_HEIGHT = 84;
inline constexpr int STATUS_GIF_FRAME_COUNT = 60;
inline constexpr int STATUS_GIF_BYTES_PER_FRAME = 882;

static_assert(STATUS_GIF_WIDTH > 0, "Status GIF width must be positive");
static_assert(STATUS_GIF_HEIGHT > 0, "Status GIF height must be positive");
static_assert(STATUS_GIF_FRAME_COUNT > 1, "Status GIF needs multiple frames");
static_assert(STATUS_GIF_BYTES_PER_FRAME ==
                  (STATUS_GIF_WIDTH * STATUS_GIF_HEIGHT + 7) / 8,
              "Status GIF frame byte count mismatch");
