// 声明 UI 构建、刷新、绘图和设置页交互的公共接口。
#pragma once
#include "lvgl.h"

#include "ui_bitmap.h"
#include "ui_boot_screen.h"
#include "ui_canvas_primitives.h"
#include "ui_clock_runtime.h"
#include "ui_clock_weather_text.h"
#include "ui_dseg_clock.h"
#include "ui_history_chart.h"
#include "ui_inverted_clock_card.h"
#include "ui_object_refs.h"
#include "ui_page_state.h"
#include "ui_progress.h"
#include "ui_settings_actions.h"
#include "ui_settings_feedback.h"
#include "ui_settings_navigation.h"
#include "ui_status_gif.h"
#include "ui_task.h"
#include "ui_task_notify.h"
#include "ui_time_format.h"
#include "ui_widgets.h"
#include "ui_work_page_catalog.h"
#include "ui_work_pages.h"
#include "ui_work_status.h"
