// 保留历史应用常量与契约的聚合兼容入口；生产实现应直接包含真实所有者头。
#pragma once
#include <ctype.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>

#include "esp_event.h"
#include "esp_crt_bundle.h"
#include "esp_http_client.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "esp_mac.h"
#include "esp_netif.h"
#include "esp_ota_ops.h"
#include "esp_pm.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "esp_sntp.h"
#include "esp_wifi.h"
#include "miniz.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "nvs.h"
#include "nvs_flash.h"
#include "cJSON.h"
#include "mbedtls/sha256.h"

#include "active_work_page_state.h"
#include "app_display_config.h"
#include "app_metadata.h"
#include "app_network_config.h"
#include "app_runtime_timing.h"
#include "app_time_constants.h"
#include "app_event_group.h"
#include "work_page_ids.h"
#include "battery_policy.h"
#include "battery_runtime_state.h"
#include "lvgl_bsp.h"
#include "dseg_digits.h"
#include "network_diagnostics_catalog.h"
#include "daily_saying_contract.h"
#include "weather_city_contract.h"
#include "weather_types.h"
#include "ota_download_policy.h"
#include "ota_flow_policy.h"
#include "ota_manifest_limits.h"
#include "sensor_history_types.h"
#include "status_gif_contract.h"
#include "ui_fonts.h"
#include "ui_icons.h"
#include "ui_settings_contract.h"
